Algoritmo "EXERCICIO 65 - "
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/09/2024
Var
   // Seção de Declarações das variáveis
   cont:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Para cont<- 100 ate 0 passo -10 faca
      escreva(cont)
   FimPara
   escreva(" Acabou!")

Fimalgoritmo