Algoritmo " Exercicio 64 -"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/09/2024
Var
   // Seção de Declarações das variáveis
   cont:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Para cont <-0 ate 40 passo 5 faca
      escreva(cont)
   FimPara
   escreva(" Acabou!")

Fimalgoritmo